"""empty message

Revision ID: 61ea127fcbd6
Revises: 
Create Date: 2026-06-01 19:54:04.581369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61ea127fcbd6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comandas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cliente', sa.String(length=100), nullable=False),
    sa.Column('mesa', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('horarioPedido', sa.DateTime(), nullable=False),
    sa.Column('horarioPagamento', sa.DateTime(), nullable=True),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('observacao', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('preco_venda', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itens_comanda',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('comanda_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('valor_unitario', sa.Float(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['comanda_id'], ['comandas.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itens_comanda')
    op.drop_table('produtos')
    op.drop_table('comandas')
    # ### end Alembic commands ###
